"""Property / Space — architecture/03-development-domain.md §1, Sprint 5
slice: no development_id/building_id/floor_id yet, since those tables
don't exist until Sprint 6 (Development Hierarchy). A property created
standalone now (e.g. existing stock, no development context) is exactly
as valid as one created through a development later — those FK columns
get added as nullable ALTER TABLEs in Sprint 6, the same way
Dataset.source_file_document_id was added once Document existed
(Sprint 4), not modelled with a placeholder now.

Every field inherited from ProvenanceMixin (source_type,
source_dataset_id, import_job_id, created_by, ...) is genuinely
populated here — this is the mixin's first real consumer.
"""

import enum
import uuid

from sqlalchemy import Enum, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base
from app.core.provenance import ProvenanceMixin


class PropertyStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    READY_FOR_HANDOVER = "READY_FOR_HANDOVER"
    HANDED_OVER = "HANDED_OVER"
    OPERATIONAL = "OPERATIONAL"
    VOID = "VOID"
    OCCUPIED = "OCCUPIED"
    DISPOSED = "DISPOSED"


class Property(Base, ProvenanceMixin):
    __tablename__ = "properties"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    property_reference: Mapped[str] = mapped_column(String(32))
    # External/official identifier — never generated by DataLume, only
    # ever supplied. The full external_references model (architecture 03
    # §3) formalises this distinction for every identifier type in
    # Sprint 7; a plain nullable column is the honest Sprint 5 version of
    # the same rule for the one identifier that matters here.
    uprn: Mapped[str | None] = mapped_column(String(32), nullable=True)
    address: Mapped[str] = mapped_column(String(500))
    postcode: Mapped[str | None] = mapped_column(String(16), nullable=True)
    property_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[PropertyStatus] = mapped_column(Enum(PropertyStatus), default=PropertyStatus.OPERATIONAL)


class Space(Base, ProvenanceMixin):
    __tablename__ = "spaces"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    property_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("properties.id"))
    name: Mapped[str] = mapped_column(String(255))
    space_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
