"""Development hierarchy — architecture/03-development-domain.md §1.

DEVELOPMENT -> BUILDING -> FLOOR -> PROPERTY -> SPACE, every level except
Property optional (spec: "do not require every customer to use every
hierarchy level"). A property or building created standalone (no
development context — e.g. existing stock, or a managing agent with no
new-build data) is exactly as valid as one created through a full
development; that's why every parent FK below is nullable, not why they
were missing before Sprint 6 — Sprint 5 just hadn't built the parent
tables yet (see git history on this file for that note).

Every field inherited from ProvenanceMixin (source_type,
source_dataset_id, import_job_id, created_by, ...) is genuinely
populated — Property/Space were the mixin's first consumers (Sprint 5),
Development/Building/Floor are new consumers this sprint.
"""

import enum
import uuid
from datetime import date

from sqlalchemy import CheckConstraint, Date, Enum, Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base
from app.core.provenance import ProvenanceMixin


class DevelopmentStatus(str, enum.Enum):
    CONCEPT = "CONCEPT"
    DESIGN = "DESIGN"
    PRE_CONSTRUCTION = "PRE_CONSTRUCTION"
    CONSTRUCTION = "CONSTRUCTION"
    HANDOVER = "HANDOVER"
    COMPLETED = "COMPLETED"
    OPERATIONAL = "OPERATIONAL"
    CANCELLED = "CANCELLED"


class BuildingStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    COMPLETED = "COMPLETED"
    OPERATIONAL = "OPERATIONAL"


class PropertyStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    READY_FOR_HANDOVER = "READY_FOR_HANDOVER"
    HANDED_OVER = "HANDED_OVER"
    OPERATIONAL = "OPERATIONAL"
    VOID = "VOID"
    OCCUPIED = "OCCUPIED"
    DISPOSED = "DISPOSED"


# External/official identifiers below (planning_reference,
# building_control_reference, bsr_reference, uprn) are never generated by
# DataLume, only ever supplied. The full external_references model
# (architecture 03 §3) formalises this distinction for every identifier
# type in Sprint 7; plain nullable columns are the honest interim version
# of the same rule, same as Property.uprn since Sprint 5.


class Development(Base, ProvenanceMixin):
    __tablename__ = "developments"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    development_reference: Mapped[str] = mapped_column(String(32))
    name: Mapped[str] = mapped_column(String(255))
    description: Mapped[str | None] = mapped_column(String(2000), nullable=True)
    address: Mapped[str | None] = mapped_column(String(500), nullable=True)
    postcode: Mapped[str | None] = mapped_column(String(16), nullable=True)
    region: Mapped[str | None] = mapped_column(String(128), nullable=True)
    developer: Mapped[str | None] = mapped_column(String(255), nullable=True)
    principal_designer: Mapped[str | None] = mapped_column(String(255), nullable=True)
    principal_contractor: Mapped[str | None] = mapped_column(String(255), nullable=True)
    employer_agent: Mapped[str | None] = mapped_column(String(255), nullable=True)
    number_of_planned_properties: Mapped[int | None] = mapped_column(Integer, nullable=True)
    planned_start_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    planned_completion_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    actual_completion_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    status: Mapped[DevelopmentStatus] = mapped_column(Enum(DevelopmentStatus), default=DevelopmentStatus.CONCEPT)
    planning_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)
    building_control_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)
    bsr_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)


class Building(Base, ProvenanceMixin):
    __tablename__ = "buildings"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    development_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("developments.id"), nullable=True)
    building_reference: Mapped[str] = mapped_column(String(32))
    name: Mapped[str] = mapped_column(String(255))
    building_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    address: Mapped[str | None] = mapped_column(String(500), nullable=True)
    height: Mapped[float | None] = mapped_column(Float, nullable=True)
    storeys: Mapped[int | None] = mapped_column(Integer, nullable=True)
    construction_type: Mapped[str | None] = mapped_column(String(128), nullable=True)
    planned_completion: Mapped[date | None] = mapped_column(Date, nullable=True)
    actual_completion: Mapped[date | None] = mapped_column(Date, nullable=True)
    building_control_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)
    bsr_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[BuildingStatus] = mapped_column(Enum(BuildingStatus), default=BuildingStatus.PLANNED)


class Floor(Base, ProvenanceMixin):
    __tablename__ = "floors"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    building_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("buildings.id"))
    name: Mapped[str] = mapped_column(String(64))
    level_index: Mapped[int | None] = mapped_column(Integer, nullable=True)


class Property(Base, ProvenanceMixin):
    __tablename__ = "properties"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    development_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("developments.id"), nullable=True)
    building_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("buildings.id"), nullable=True)
    floor_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("floors.id"), nullable=True)
    property_reference: Mapped[str] = mapped_column(String(32))
    uprn: Mapped[str | None] = mapped_column(String(32), nullable=True)
    address: Mapped[str] = mapped_column(String(500))
    postcode: Mapped[str | None] = mapped_column(String(16), nullable=True)
    property_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[PropertyStatus] = mapped_column(Enum(PropertyStatus), default=PropertyStatus.OPERATIONAL)


class Space(Base, ProvenanceMixin):
    __tablename__ = "spaces"
    __table_args__ = (
        CheckConstraint("property_id IS NOT NULL OR building_id IS NOT NULL", name="ck_space_has_a_parent"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    organisation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organisations.id"))
    # A space is a room/unit inside a property OR a communal area
    # belonging directly to a building (spec: "spaces(... property_id
    # NULL, building_id NULL ...)") — never neither, enforced above.
    property_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("properties.id"), nullable=True)
    building_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("buildings.id"), nullable=True)
    name: Mapped[str] = mapped_column(String(255))
    space_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
