"""DocumentStorage adapter boundary — architecture/00 §5 and 02 §4.

Unlike Stripe (Sprint 2) and a real Redis-backed job queue (Sprint 3),
local-disk storage needs no external credentials to implement and
verify for real — so this one isn't deferred behind a Null stub.
LocalFilesystemStorage is a genuine, tested implementation, suitable for
local dev and this environment. Swapping in S3Storage/AzureBlobStorage
for production is a second Protocol implementation behind
get_document_storage(), exactly like BillingProvider — no caller
(app/documents/router.py) depends on anything beyond the Protocol.
"""

import hashlib
from pathlib import Path
from typing import Protocol

from app.core.config import get_settings


class DocumentStorage(Protocol):
    def save(self, key: str, content: bytes) -> None: ...
    def read(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class LocalFilesystemStorage:
    def __init__(self, base_dir: Path):
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        # Reject anything that could escape base_dir (path traversal via a
        # crafted key) — keys are generated by this app, never taken
        # directly from user input, but this is cheap insurance.
        path = (self.base_dir / key).resolve()
        if self.base_dir.resolve() not in path.parents and path != self.base_dir.resolve():
            raise ValueError(f"Invalid storage key: {key}")
        return path

    def save(self, key: str, content: bytes) -> None:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)

    def read(self, key: str) -> bytes:
        return self._resolve(key).read_bytes()

    def delete(self, key: str) -> None:
        path = self._resolve(key)
        if path.exists():
            path.unlink()


def sha256_hex(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def get_document_storage() -> DocumentStorage:
    settings = get_settings()
    return LocalFilesystemStorage(Path(settings.local_storage_dir))
