"use client";

import { useEffect, useState } from "react";
import { inputStyle, primaryBtn } from "@/components/formStyles";
import { api, ApiError, type ReferencePattern } from "@/lib/api";

const SELECTED_ORG_KEY = "datalume.selectedOrganisationId";

const ENTITY_LABELS: Record<string, string> = {
  DEVELOPMENT: "Developments",
  BUILDING: "Buildings",
  PROPERTY: "Properties",
  DOCUMENT: "Documents",
};

function orgId(): string | null {
  return typeof window === "undefined" ? null : window.localStorage.getItem(SELECTED_ORG_KEY);
}

export default function OrganisationPage() {
  const [patterns, setPatterns] = useState<ReferencePattern[] | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState<string | null>(null);
  const [rowError, setRowError] = useState<Record<string, string>>({});

  async function refresh() {
    const id = orgId();
    if (!id) return;
    const list = await api.listReferencePatterns(id);
    setPatterns(list);
    setDrafts(Object.fromEntries(list.map((p) => [p.entity_type, p.pattern])));
  }

  useEffect(() => {
    (async () => {
      const id = orgId();
      if (!id) {
        setLoadError("No organisation selected.");
        return;
      }
      try {
        await refresh();
      } catch {
        setLoadError("Couldn't load organisation settings.");
      }
    })();
  }, []);

  async function onSave(entityType: string) {
    const id = orgId();
    const draft = drafts[entityType];
    if (!id || !draft) return;
    setSaving(entityType);
    setRowError((prev) => ({ ...prev, [entityType]: "" }));
    try {
      await api.updateReferencePattern(id, entityType, draft);
      await refresh();
    } catch (err) {
      const message =
        err instanceof ApiError && err.status === 403
          ? "Only an owner or admin can change reference patterns."
          : "Couldn't save that pattern — it must include a {sequence} placeholder.";
      setRowError((prev) => ({ ...prev, [entityType]: message }));
    } finally {
      setSaving(null);
    }
  }

  if (loadError) {
    return <div style={{ color: "var(--text-secondary)" }}>{loadError}</div>;
  }

  return (
    <div style={{ maxWidth: 720 }}>
      <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0, marginBottom: 4 }}>Organisation</h1>
      <p style={{ color: "var(--text-secondary)", marginBottom: 24 }}>
        Internal reference formats — every reference below is generated by DataLume, never an official
        identifier. Only an owner or admin can change these.
      </p>

      <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12 }}>Reference patterns</h2>
      {patterns === null ? (
        <div style={{ color: "var(--text-secondary)" }}>Loading…</div>
      ) : (
        <div
          style={{
            background: "var(--bg-card)",
            border: "1px solid var(--border-subtle)",
            borderRadius: "var(--radius-card)",
            padding: 20,
          }}
        >
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
            <thead>
              <tr style={{ textAlign: "left", color: "var(--text-secondary)" }}>
                <th style={{ padding: "8px" }}>Type</th>
                <th style={{ padding: "8px" }}>Pattern</th>
                <th style={{ padding: "8px" }}>Next sequence</th>
                <th style={{ padding: "8px" }}></th>
              </tr>
            </thead>
            <tbody>
              {patterns.map((p) => (
                <tr key={p.entity_type} style={{ borderTop: "1px solid var(--border-subtle)" }}>
                  <td style={{ padding: "8px" }}>{ENTITY_LABELS[p.entity_type] ?? p.entity_type}</td>
                  <td style={{ padding: "8px" }}>
                    <input
                      aria-label={`${ENTITY_LABELS[p.entity_type] ?? p.entity_type} identifier pattern`}
                      style={{ ...inputStyle, fontFamily: "monospace" }}
                      value={drafts[p.entity_type] ?? ""}
                      onChange={(e) => setDrafts((prev) => ({ ...prev, [p.entity_type]: e.target.value }))}
                    />
                    {rowError[p.entity_type] && (
                      <div style={{ color: "var(--color-critical)", fontSize: 12, marginTop: 4 }}>
                        {rowError[p.entity_type]}
                      </div>
                    )}
                  </td>
                  <td style={{ padding: "8px", color: "var(--text-secondary)" }}>{p.next_sequence}</td>
                  <td style={{ padding: "8px" }}>
                    <button
                      style={{ ...primaryBtn, padding: "4px 12px" }}
                      onClick={() => onSave(p.entity_type)}
                      disabled={saving === p.entity_type || drafts[p.entity_type] === p.pattern}
                    >
                      {saving === p.entity_type ? "Saving…" : "Save"}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
